# Generated by Django 6.0.4 on 2026-05-04 12:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='nascimento',
        ),
        migrations.AddField(
            model_name='cliente',
            name='datadenascimento',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='data de nascimento'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cpf',
            field=models.CharField(max_length=14, verbose_name='cpf'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefone',
            field=models.CharField(max_length=14, verbose_name='telefone'),
        ),
    ]
